### PR TITLE
Uncomment `applyWindow` helper

### PR DESCRIPTION
**Pull request by bvanderdrift**
Using your library I noticed I was writing an `applyWindow` helper myself. Upon inspecting your code I noticed it already existed but was commented out.

This PR functions as a suggestion to uncomment it, since I believe it has high re-usability in combination with the functions. Let me know what you think.

By accident my IDE also ran Prettify over your code, that it the reason you see some styling changed. Let me know if you prefer to have a more pure edit and I'll remove the Prettify edit.

### CODE REVIEW

**Comment by dy** [comment]
@bvanderdrift yes, please remove style formatting, that is not relevant to the PR

**Comment by rreusser** [comment]
Thanks, @bvanderdrift! In an ideal world, this would live in a larger ecosystem of tools so it wouldn't have to manage currying itself, but I think it makes good sense here. 👍

I'd appreciate if you could remove the prettier formatting though. I'd be totally fine with prettier formatting in general, but as its own PR since it makes it difficult to figure which parts have _actually_ changed here.

One final nitpick is if you could leave out the version bump from the PR itself. When multiple PRs come though it's usually easier to focus on the content, then bump the version and release in a separate step. (FWIW I'll probably switch from mocha to tape while I'm at it so that there are probably a couple more changes coming through after this PR 😄)

Thanks so much though! Glad to know it's useful.

**Comment by bvanderdrift** [comment]
@dy @rreusser back to you people. I removed the version bump and the Prettier style edits! :)

@rreusser glad to help, always like these little toolboxes of functions.

**Comment by rreusser** [comment]
Oh no, it looks like I dropped the ball here. Apologies I didn't get this merged in a reasonable amount of time. Lost the notification and forgot about it. Thanks nonetheless, @bvanderdrift and @dy!

**Comment by bvanderdrift** [comment]
No worries! It's in :tada:!

**Pull request merged**
